<?php
/**
 * plugin Generate objects for Cotonti Siena
 * 
 * @package objects
 * @version 0.9.13
 * @author ElNinjo
 * @copyright tesidex.com
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['info_desc'] = 'Plugin Info';

$L['cfg_string'] = array('string', 'string desc');
$L['cfg_select'] = array('select', 'select desc');
$L['cfg_select_params'] = array('one', 'two', 'three');
$L['cfg_radio'] = array('radio', 'radio desc');
$L['cfg_separatortext'] = 'separator text';
$L['cfg_range'] = array('range', 'range desc');
$L['cfg_textarea'] = array('textarea', 'textarea desc');

