<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=standalone
 * [END_COT_EXT]
 */
 
/**
 * plugin Generate objects for Cotonti Siena
 * 
 * @package objects
 * @version 0.9.13
 * @author ElNinjo
 * @copyright tesidex.com
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('objects', 'plug');
require_once cot_incfile('objects', 'plug');
require_once cot_incfile('objects', 'plug', 'resources');
$t = new XTemplate(cot_tplfile('objects', 'plug'));
$t->parse('MAIN');
$t->out('MAIN');

